// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZigyCDupQixaLPlxGMRlwM8creucGmOA',
    appId: '1:592206951593:web:3a13d5312de374d9ab65b8',
    messagingSenderId: '592206951593',
    projectId: 'younger-maps',
    authDomain: 'younger-maps.firebaseapp.com',
    databaseURL: 'https://younger-maps-default-rtdb.firebaseio.com',
    storageBucket: 'younger-maps.appspot.com',
    measurementId: 'G-M7VZY11NVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8bDZhZwFEt4CIfJqI4lHAdCNEFl-M-M',
    appId: '1:592206951593:android:ee41632a599571acab65b8',
    messagingSenderId: '592206951593',
    projectId: 'younger-maps',
    databaseURL: 'https://younger-maps-default-rtdb.firebaseio.com',
    storageBucket: 'younger-maps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECNALWcLSrNpJM48B2oHyIyDXzSKGrkU',
    appId: '1:592206951593:ios:0b718f58ffb24952ab65b8',
    messagingSenderId: '592206951593',
    projectId: 'younger-maps',
    databaseURL: 'https://younger-maps-default-rtdb.firebaseio.com',
    storageBucket: 'younger-maps.appspot.com',
    iosClientId: '592206951593-uh1t06suqq2gedi6kclkj8g496vrraag.apps.googleusercontent.com',
    iosBundleId: 'com.example.youngerDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECNALWcLSrNpJM48B2oHyIyDXzSKGrkU',
    appId: '1:592206951593:ios:eacde8edcda4d36fab65b8',
    messagingSenderId: '592206951593',
    projectId: 'younger-maps',
    databaseURL: 'https://younger-maps-default-rtdb.firebaseio.com',
    storageBucket: 'younger-maps.appspot.com',
    iosClientId: '592206951593-l8m23ehfbirp8mefjq2p3eob0j9j7mcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.youngerDelivery.RunnerTests',
  );
}
